version: '3.0'

services:
  app:
    extends:
      file: docker-compose.dev.yml
      service: app
    command: npx nx run-tests backend

  postgres:
    extends:
      file: docker-compose.dev.yml
      service: postgres
    ports:
     - "5432:5432"

  redis:
    extends:
      file: docker-compose.dev.yml
      service: redis
    ports:
     - "6379:6379"

volumes:
  postgres_data_dev:
  redis_data_dev:

networks:
  activepieces_dev:
