## **************** DOCUMENTATION ****************
##
## Please refer to the documentation for more information on how to use this file. 
## https://www.activepieces.com/docs/contributing/development-setup/docker-compose
##
## ***********************************************
version: '3.0'

services:

  postgres:
    image: postgres:14.4
    ports:
      - "5432:5432"
    container_name: postgres
    environment:
      POSTGRES_DB: activepieces
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: A79Vm5D4p2VQHOp2gd5
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - activepieces_dev
    #command: -c log_statement=all -c shared_preload_libraries=auto_explain -c auto_explain.log_min_duration=0

  redis:
    image: redis:7.0.7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - activepieces_dev

volumes:
  postgres_data_dev:
  redis_data_dev:

networks:
  activepieces_dev:
