variables:
  OUTPUT_DIR: dist/piece-builder

services:
  - docker:dind

stages:
  - dependencies
  - build
  - deploy

install_dependencies:
  image: node:16-alpine
  stage: dependencies
  script:
    - npm install
  except:
    - master
    - staging
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules

build_files:
  image: node:16-alpine
  stage: build
  script:
    - npm run build:review
  except:
    - master
    - staging
  artifacts:
    paths:
      - $CI_PROJECT_DIR/$OUTPUT_DIR
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules

deploy_to_server:
  stage: deploy
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $MACHINE_IP >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
  - ssh root@$MACHINE_IP "/bin/bash -s " < gen-nginx.sh $CI_COMMIT_REF_NAME
  - ssh root@$MACHINE_IP "sudo systemctl reload nginx"
  - scp -r $CI_PROJECT_DIR/$OUTPUT_DIR/* root@$MACHINE_IP:/home/admin/reviews/$CI_COMMIT_REF_NAME
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_COMMIT_REF_NAME.activepieces.xyz
    on_stop: stop_review
  except:
    - master
    - staging

stop_review:
  stage: deploy
  script:
    - ssh root@$MACHINE_IP "rm -rf /home/admin/reviews/$CI_COMMIT_REF_NAME"
    - ssh root@$MACHINE_IP "rm -rf /etc/nginx/sites-enabled/$CI_COMMIT_REF_NAME"
  variables:
    GIT_STRATEGY: none
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  tags:
    - nginx
    - review-apps
    - deploy
