name: Build Everything

on:
  push:

jobs:
  Build-Everything:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: install npm deps
        run: npm ci

      - name: check for engine compilation errors
        run: npx tsc -p packages/engine/tsconfig.lib.json --noEmit

      - name: build everything
        run: npx nx run-many --target=build
