name: Build Everything

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/**'
  push:
    branches:
      - main
    paths:
      - 'packages/**'

jobs:
  Build-Everything:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - uses: nrwl/nx-set-shas@v3
      - run: npx nx affected -t lint --parallel=5
      - run: npx nx affected -t build --parallel=5
