name: Build Everything

on:
  push:

jobs:
  Build-Everything:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: install npm deps
        run: npm ci

      - name: lint the backend
        run: npx nx lint backend

      - name: build everything
        run: npx nx run-many --target=build
