name: Release backend

on:
  push:
    branches:
      - dev
      - feature-automate-worker-build-#80

jobs:
  Release-Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download worker deps
        run: cd src/worker && npm ci

      - name: Build and copy worker to backend
        run: cd src/worker && npx nx run-many --target=build 

      - name: Install JDK v11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set RELEASE env var from backend-loader/pom.xml
        run: echo RELEASE=$(mvn help:evaluate --file src/backend/backend-loader/pom.xml -Dexpression=project.version -q -DforceStdout) >> $GITHUB_ENV

      - name: Fail if tag already exists
        run: "! docker manifest inspect activepieces/backend:${{ env.RELEASE }}"

      - name: Package jar file
        run: mvn --batch-mode --update-snapshots --file src/backend/pom.xml package

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: src/backend
          push: true
          tags: "activepieces/backend:${{ env.RELEASE }}"
