name: Release Backend with Depot

on:
  push:
    branches:
      - depot

jobs:
  Release-Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set RELEASE env var from package.json
        run: echo RELEASE=$(node --print "require('./packages/backend/package.json').version") >> $GITHUB_ENV

      - name: Fail if tag already exists
        run: "! docker manifest inspect activepieces/test:${{ env.RELEASE }}"

      - uses: depot/setup-action@v1

      - name: build backend
        run: npx nx build backend

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
      - uses: depot/build-push-action@v1
        with:
          context: .
          file: ./backend.dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            activepieces/test:${{ env.RELEASE }}
            activepieces/test:latest
