name: Release AP base

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'image tag'
        required: true

jobs:
  Release-AP-Base:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Fail if tag already exists
        run: "! docker manifest inspect activepieces/ap-base:${{ inputs.tag }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./ap-base.dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            activepieces/ap-base:${{ inputs.tag }}
            activepieces/ap-base:latest
