name: Release frontend

on:
  push:
    branches:
      - main
      - dev
      - feature-automate-releases-#74

jobs:
  Release-Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set RELEASE env var from package.json
        run: echo RELEASE=$(node --print "require('./src/frontend/package.json').version") >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: src/frontend
          push: true
          tags: "activepieces/frontend:${{ env.RELEASE }}"
