name: Release Frontend

on:
  push:
    branches:
      - dev
      - feature-integrated-repo-pipeline

jobs:
  Release-Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set RELEASE env var from package.json
        run: echo RELEASE=$(node --print "require('./packages/frontend/package.json').version") >> $GITHUB_ENV

      - name: Fail if tag already exists
        run: "! docker manifest inspect activepieces/frontend-ee:${{ env.RELEASE }}"

      - name: install npm deps
        run: npm ci

      - name: build frontend
        run: npx nx build frontend

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./frontend.dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            activepieces/frontend:${{ env.RELEASE }}
            activepieces/frontend:latest
