name: Release Pieces

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/pieces/**'

jobs:
  Release-Pieces:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: install npm deps
        run: npm ci

      - name: build packages
        run: npx nx run-many --target=build

      - name: copy project .npmrc to user level
        run: cp .npmrc $HOME/.npmrc

      - name: update pieces metadata
        run: npx nx update-pieces-metadata pieces-apps
        env:
          DO_SPACES_KEY: ${{ secrets.DO_SPACES_KEY }}
          DO_SPACES_SECRET: ${{ secrets.DO_SPACES_SECRET }}
