name: Release frontend

on:
  push:
    branches:
      - main
      - dev
      - feature-automate-releases-#74

jobs:
  Release-Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Get version from package.json
        run: echo "RELEASE=0.0.14" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: src/frontend
          push: true
          tags: "activepieces/frontend:${{ env.RELEASE }}""
