name: Validate publishable packages

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/**'

jobs:
  validate-publishable-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: validate publishable packages
        run: npx ts-node tools/scripts/validate-publishable-packages.ts
